### ISSUE TITLE
Getting requirements to build wheel ... error   error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by BlackKuroh** [A-DYB/smeeta-tracker-2#2]
Hello,
following step 4 of instructions, and I get back this error after "Installing build dependencies ... done"

Getting requirements to build wheel ... error
error: subprocess-exited-with-error
  × Getting requirements to build wheel did not run successfully.
 note: This error originates from a subprocess, and is likely not a problem with pip.
 
 any tips on what to do?

**Comment by A-DYB** [comment]
Not sure if this will fix the issue, but from what I have read you can try "pip install wheel". 

However, I have just released the program with some new features as an exe because the installation process is not straightforward if you are running as a python script.

So I would recommend downloading the exe from here:  https://github.com/A-DYB/smeeta-tracker-2/releases/tag/v1.0.0

**Comment by BlackKuroh** [comment]
Hello,
Oh great that worked like a charm.
Tried the exe version and it loaded instantly, nice!
thank you
